name: Release
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Run release command
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        npx release-it --ci --dry-run
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
